// Autogenerated by ruby localization script

#import "ILMStringsManager.h"

@implementation ILMStringsManager

NSString* getStringFromTable(NSString* tableName, NSString* key){return NSLocalizedStringFromTable(key, tableName, @"");}
NSString* getStringFromTableWithKey(NSString* tableName, NSString* key){return NSLocalizedStringFromTable(key, tableName, @"");}
+ (NSString *)getGeneralAlertTryAgainLaterString{return getStringFromTable(GeneralLocalizationTable,@"general_alert_try_again_later");}
+ (NSString *)getGeneralCancelButtonTitleString{return getStringFromTable(GeneralLocalizationTable,@"general_cancel_button_title");}
+ (NSString *)getGeneralCloseButtonTitleString{return getStringFromTable(GeneralLocalizationTable,@"general_close_button_title");}
+ (NSString *)getGeneralDeleteButtonTitleString{return getStringFromTable(GeneralLocalizationTable,@"general_delete_button_title");}
+ (NSString *)getGeneralDoneButtonTitleString{return getStringFromTable(GeneralLocalizationTable,@"general_done_button_title");}
+ (NSString *)getGeneralErrorTitleString{return getStringFromTable(GeneralLocalizationTable,@"general_error_title");}
+ (NSString *)getGeneralSaveButtonTitleString{return getStringFromTable(GeneralLocalizationTable,@"general_save_button_title");}
+ (NSString *)getGeneralTimeBeginningButtonTitleString{return getStringFromTable(GeneralLocalizationTable,@"general_time_beginning_button_title");}
+ (NSString *)getGeneralTimeEndButtonTitleString{return getStringFromTable(GeneralLocalizationTable,@"general_time_end_button_title");}

@end
