// Autogenerated by ruby localization script

#import <UIKit/UIKit.h>

static NSString* GeneralLocalizationTable = @"GeneralLocalizationTable";

@interface ILMStringsManager : NSObject


#pragma mark - General
+ (NSString *)getGeneralAlertTryAgainLaterString;
+ (NSString *)getGeneralCancelButtonTitleString;
+ (NSString *)getGeneralCloseButtonTitleString;
+ (NSString *)getGeneralDeleteButtonTitleString;
+ (NSString *)getGeneralDoneButtonTitleString;
+ (NSString *)getGeneralErrorTitleString;
+ (NSString *)getGeneralSaveButtonTitleString;
+ (NSString *)getGeneralTimeBeginningButtonTitleString;
+ (NSString *)getGeneralTimeEndButtonTitleString;

@end
